site_name: Not Much Js
site_url: https://notmuchjs.info

theme:
  name: material
  language: en
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

#nav:
#  - Home:
#      - index.md
#      - 'Htmx' : htmx.md
#      - intercooler.md
#      - liveview.md
#      - unpoly.md
#
#  - htmx.md
#  - intercooler.md
#  - liveview.md
#  - unpoly.md

